# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Rania218"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "twitter"
url = "https://www.linkedin.com/in/rania-moutee-52a1321a2/"

[social.params]
icon = "brand-twitter"
